In [1]:

import numpy as np
from scipy.linalg import null_space
from sympy import Matrix


In [2]:
#definisco la matrice

M = np.array([
[ 6 , 12, 4 , 4 ,  2 , 0 , 0 , 0 , 2 , 0 , 2 , 0 , 0 , 0 , 0 ],

[ 4 , 12, 0 , 0 ,  8 , 0 , 0 , 0 , 4 , 4 , 0 , 0 , 0 , 0 , 0 ],

[ 8 , 8 , 8 , 8 ,  0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 ],

[ 8 , 12, 4 , 0 ,  4 , 0 , 0 , 0 , 0 , 4 , 0 , 0 , 0 , 0 , 0 ],

[ 6 , 4 , 6 , 8 ,  0 , 2 , 2 , 2 , 0 , 0 , 0 , 2 , 0 , 0 , 0 ],

[ 4 , 2 , 6 , 2 ,  2 , 2 , 2 , 2 , 4 , 2 , 0 , 2 , 0 , 0 , 2 ],

[ 4 , 4 , 4 , 4 ,  2 , 2 , 2 , 2 , 2 , 2 , 2 , 0 , 0 , 2 , 0 ],

[ 4 , 2 , 4 , 2 ,  2 , 4 , 2 , 4 , 2 , 2 , 0 , 2 , 2 , 0 , 0 ],

[ 12, 4 , 4 , 4 ,  0 , 0 , 4 , 4 , 0 , 0 , 0 , 0 , 0 , 0 , 0 ],

[ 12, 4 , 4 , 4 ,  0 , 0 , 4 , 4 , 0 , 0 , 0 , 0 , 0 , 0 , 0 ],

[ 10, 6 , 6 , 2 ,  0 , 2 , 0 , 2 , 0 , 2 , 2 , 0 , 0 , 0 , 0 ],

[ 8 , 0 , 8 , 0 ,  0 , 8 , 0 , 0 , 0 , 0 , 0 , 8 , 0 , 0 , 0 ],

[ 0 , 0 , 0 , 0 ,  8 , 0 , 0 , 8 , 0 , 0 , 8 , 0 , 8 , 0 , 0 ],

[ 8 , 4 , 4 , 0 ,  4 , 4 , 0 , 4 , 4 , 0 , 0 , 0 , 0 , 0 , 0 ],

[ 0 , 8 , 16, 0 ,  0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 8 , 0 , 0 ],
    
]) 


In [3]:
#S=M - (32+0.j)*np.identity(15)
#S.nullspace()

autovalori, autovettori =np.linalg.eig(M)

#printo gli autovalori, il primo è 32
autovalori

array([ 3.20000000e+01+0.j        ,  1.00210212e+01+0.j        ,
        6.62201886e+00+4.76220694j,  6.62201886e+00-4.76220694j,
        6.77968999e+00+0.j        , -3.41972099e+00+4.06648896j,
       -3.41972099e+00-4.06648896j, -4.04917874e+00+0.j        ,
        3.34137611e-01+3.11601943j,  3.34137611e-01-3.11601943j,
        2.50305097e+00+0.j        , -1.61792301e+00+0.j        ,
       -3.54765705e-01+0.83098304j, -3.54765705e-01-0.83098304j,
       -1.71934773e-15+0.j        ])

In [4]:
#printo il primo autovettore (di autovalore 32)
autovettori[:,0]

array([-0.25819889+0.j, -0.25819889+0.j, -0.25819889+0.j, -0.25819889+0.j,
       -0.25819889+0.j, -0.25819889+0.j, -0.25819889+0.j, -0.25819889+0.j,
       -0.25819889+0.j, -0.25819889+0.j, -0.25819889+0.j, -0.25819889+0.j,
       -0.25819889+0.j, -0.25819889+0.j, -0.25819889+0.j])

In [5]:
#verifico che M*v = 32v
np.dot(M,autovettori[:,0])

array([-8.26236447+0.j, -8.26236447+0.j, -8.26236447+0.j, -8.26236447+0.j,
       -8.26236447+0.j, -8.26236447+0.j, -8.26236447+0.j, -8.26236447+0.j,
       -8.26236447+0.j, -8.26236447+0.j, -8.26236447+0.j, -8.26236447+0.j,
       -8.26236447+0.j, -8.26236447+0.j, -8.26236447+0.j])